### PR TITLE
Fixes issue updating files when proxy is running. Closes #244

### LINKED ISSUE #244: [BUG]: Unable to update errors file whilst proxy is running
## Description

When making changes to the errors file whilst the proxy is running, exceptions are thrown in the proxy output and the file is not reloaded.

## Expected behaviour

Proxy reloads the content of the errors file automatically.

## Actual behaviour

An error is thrown on the first change but the file is reloaded.
An error is thrown on the second change but the file is not reloaded.
An error is thrown on the third change, the file is locked and cannot be overridden.

image

## Environment

OS: Windows 11
Shell: PowerShell
MGDP: 0.6.0

## Steps to reproduce

1. Add a file called `openai.json` to the `presets` folder.

```json
{
  "plugins": [
    {
      "name": "GenericRandomErrorPlugin",
      "enabled": true,
      "pluginPath": "GraphProxyPlugins\\msgraph-developer-proxy-plugins.dll",
      "configSection": "openAI",
      "urlsToWatch": [
        "https://api.openai.com/*"
      ]
    }
  ],
  "urlsToWatch": [
  ],
  "openAI": {
    "rate": 95,
    "errorsFile": "errors-openai.json"
  },
  "labelMode": "text",
  "logLevel": "info"
}
```

2. Create a file called `errors-openai.json` in the project root.

```json
{
  "responses": [
    {
      "statusCode": 500,
      "headers": {
        "content-type": "application/json; charset=utf-8"
      },
      "body": {
        "error": {
          "message": "The server had an error while processing your request",
          "type": "requests",
          "param": null,
          "code": null
        }
      }
    },
    {
      "statusCode": 429,
      "addDynamicRetryAfter": true,
      "headers": {
        "content-type": "application/json; charset=utf-8"
      },
      "body": {
        "error": {
          "message": "The engine is currently overloaded, please try again later.",
          "type": "requests",
          "param": null,
          "code": null
        }
      }
    },
    {
      "statusCode": 429,
      "headers": {
        "content-type": "application/json; charset=utf-8"
      },
      "body": {
        "error": {
          "message": "Rate limit reached for default-text-davinci-003 in organization org-K7hT684bLccDbBRnySOoK9f2 on tokens per min. Limit: 150000.000000 / min. Current: 160000.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://beta.openai.com/account/billing to add a payment method.",
          "type": "tokens",
          "param": null,
          "code": null
        }
      }
    },
    {
      "statusCode": 429,
      "headers": {
        "content-type": "application/json; charset=utf-8"
      },
      "body": {
        "error": {
          "message": "Rate limit reached for default-text-davinci-003 in organization org-K7hT684bLccDbBRnySOoK9f2 on requests per min. Limit: 60.000000 / min. Current: 70.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://beta.openai.com/account/billing to add a payment method.",
          "type": "requests",
          "param": null,
          "code": null
        }
      }
    }    
  ]
}
```

3. Start the proxy from the project root folder using the preset configuration file.

```cmd
mgdp -c /path/to/presets/openai.json
```

4. Remove an object from the responses array in the `errors-openai.json` file. Save the file.
5. Remove an object from the responses array in the `errors-openai.json` file. Save the file.
5. Remove an object from the responses array in the `errors-openai.json` file. Save the file.

### PR DESCRIPTION
**Pull request by garrytrinder**
Closes #244

### CODE REVIEW

File: msgraph-developer-proxy-plugins/RandomErrors/GenericErrorResponsesLoader.cs [hunk 1]
```diff
@@ -26,12 +27,16 @@ internal class GenericErrorResponsesLoader : IDisposable {
         }
 
         try {
-            var responsesString = File.ReadAllText(_errorsFile);
-            var responsesConfig = JsonSerializer.Deserialize<GenericRandomErrorConfiguration>(responsesString);
-            IEnumerable<GenericErrorResponse>? configResponses = responsesConfig?.Responses;
-            if (configResponses is not null) {
-                _configuration.Responses = configResponses;
-                _logger.LogInfo($"Error responses for {configResponses.Count()} url patterns loaded from from {_configuration.ErrorsFile}");
+            using (FileStream stream = new FileStream(_errorsFile, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
```
Comment (waldekmastykarz) [inline msgraph-developer-proxy-plugins/RandomErrors/GenericErrorResponsesLoader.cs:30]: For clarity, let's add surrounding `{ }`. Other than that, good to go.

File: msgraph-developer-proxy-plugins/MockResponses/MockResponsesLoader.cs [hunk 2]
```diff
@@ -25,13 +26,18 @@ internal class MockResponsesLoader : IDisposable {
             return;
         }
 
-        try {
-            var responsesString = File.ReadAllText(_responsesFilePath);
-            var responsesConfig = JsonSerializer.Deserialize<MockResponseConfiguration>(responsesString);
-            IEnumerable<MockResponse>? configResponses = responsesConfig?.Responses;
+        try
+        {
+            using (FileStream stream = new FileStream(_responsesFilePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
```
Comment (waldekmastykarz) [inline msgraph-developer-proxy-plugins/MockResponses/MockResponsesLoader.cs:31]: For clarity, let's add surrounding `{ }`. Other than that, good to go.

**Review by waldekmastykarz — CHANGES_REQUESTED** [review]
Let's do a minor adjustment and get it in 🚀

File: msgraph-developer-proxy-plugins/MockResponses/MockResponsesLoader.cs [hunk 3]
```diff
@@ -25,13 +26,18 @@ internal class MockResponsesLoader : IDisposable {
...
-        try {
-            var responsesString = File.ReadAllText(_responsesFilePath);
-            var responsesConfig = JsonSerializer.Deserialize<MockResponseConfiguration>(responsesString);
-            IEnumerable<MockResponse>? configResponses = responsesConfig?.Responses;
-            if (configResponses is not null) {
-                _configuration.Responses = configResponses;
-                _logger.LogInfo($"Mock responses for {configResponses.Count()} url patterns loaded from {_configuration.MocksFile}");
+        try
+        {
+            using (FileStream stream = new FileStream(_responsesFilePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite)){
```
Comment (waldekmastykarz) [inline msgraph-developer-proxy-plugins/MockResponses/MockResponsesLoader.cs:31]: Let's clean this up: seems like we're missing a space between `){`

File: msgraph-developer-proxy-plugins/RandomErrors/GenericErrorResponsesLoader.cs [hunk 4]
```diff
@@ -26,12 +27,15 @@ internal class GenericErrorResponsesLoader : IDisposable {
...
 
         try {
-            var responsesString = File.ReadAllText(_errorsFile);
-            var responsesConfig = JsonSerializer.Deserialize<GenericRandomErrorConfiguration>(responsesString);
-            IEnumerable<GenericErrorResponse>? configResponses = responsesConfig?.Responses;
-            if (configResponses is not null) {
-                _configuration.Responses = configResponses;
-                _logger.LogInfo($"Error responses for {configResponses.Count()} url patterns loaded from from {_configuration.ErrorsFile}");
+            using (FileStream stream = new FileStream(_errorsFile, FileMode.Open, FileAccess.Read, FileShare.ReadWrite)) {
+                using (StreamReader reader = new StreamReader(stream)) {                var responsesString = reader.ReadToEnd();
```
Comment (waldekmastykarz) [inline msgraph-developer-proxy-plugins/RandomErrors/GenericErrorResponsesLoader.cs:31]: Let's clean this up. Seems like we're missing a new line here

**Review by waldekmastykarz — CHANGES_REQUESTED** [review]

**Review by waldekmastykarz — APPROVED** [review]
